# Generated by Django 3.2 on 2021-04-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.IntegerField()),
                ('item2', models.IntegerField()),
                ('item3', models.IntegerField()),
                ('item4', models.IntegerField()),
                ('item5', models.IntegerField()),
                ('item6', models.IntegerField()),
                ('item7', models.IntegerField()),
                ('item8', models.IntegerField()),
                ('item9', models.IntegerField()),
                ('item10', models.IntegerField()),
                ('item11', models.IntegerField()),
                ('item12', models.IntegerField()),
                ('item13', models.IntegerField()),
                ('item14', models.IntegerField()),
                ('item15', models.IntegerField()),
            ],
        ),
    ]
