# Generated by Django 3.2 on 2021-04-29 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20210429_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='itam1',
        ),
    ]
