# Generated by Django 3.2 on 2021-04-29 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_rename_phone_contact_itam1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='item1',
            new_name='Burger',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='item10',
            new_name='Chicken65',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='item11',
            new_name='Chocolate',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='item12',
            new_name='Coffee',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='item13',
            new_name='Coke',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='item14',
            new_name='FriedRice',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='item15',
            new_name='FruitJucies',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='item2',
            new_name='Manchurian',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='item3',
            new_name='Noodles',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='item4',
            new_name='Paestry',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='item5',
            new_name='Puffs',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='item6',
            new_name='Roll',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='item7',
            new_name='Smoothies',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='item8',
            new_name='Tea',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='item9',
            new_name='VegMeal',
        ),
    ]
