# Generated by Django 3.2 on 2021-04-30 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20210430_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Recipent',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
